
module.exports = [
  "lorem ipsum dolor sit amet",
  "consectetur adipiscing elit",
  "cras ultrices urna eget tellus",
  "lacinia volutpat",
  "cras efficitur risus odio",
  "et condimentum sem tempor id",
  "morbi facilisis diam arcu",
  "sit amet consectetur nisi gravida placerat",
  "phasellus tempor metus sed velit lacinia",
  "at luctus leo egestas",
  "praesent elit libero",
  "aliquet nec viverra in",
  "sagittis id nisl",
  "sed sed felis id nibh porttitor pellentesque in eu ante",
  "fusce vestibulum nulla mi",
  "eget sodales arcu consequat non",
  "in ullamcorper leo nisi",
  "et vulputate orci facilisis at",
  "pellentesque in volutpat neque",
  "morbi ut egestas urna",
  "eu tincidunt ante",
  "mauris consequat blandit nisi sed commodo",
  "fusce venenatis sodales nisi",
  "quisque ut suscipit nunc",
  "nunc quis tellus neque",
  "vestibulum massa lorem",
  "tincidunt eu mattis a",
  "ultrices ac nunc",
  "fusce nibh odio",
  "venenatis eu molestie et",
  "sollicitudin vitae lacus",
  "proin iaculis orci ut dui pulvinar",
  "a cursus ligula tempus",
  "pellentesque habitant morbi tristique senectus et",
  "cras euismod elit quis dapibus porttitor",
  "vestibulum ante ipsum primis in faucibus orci luctus",
  "duis fermentum malesuada leo sed mollis",
  "in egestas",
  "leo et faucibus imperdiet",
  "felis enim tincidunt odio",
  "eu condimentum quam justo sit amet velit",
  "sed eu ligula ut metus ultricies pharetra",
  "nullam et egestas magna",
  "duis finibus eu mauris eget fringilla",
  "sed vitae sem vel dui pretium ultrices et vitae urna",
  "pellentesque iaculis",
  "ante vitae dapibus congue",
  "nisi est finibus arcu",
  "fringilla tristique arcu turpis maximus ex",
  "aenean vitae tempus velit",
  "phasellus eget purus vel neque vehicula faucibus id sed mauris",
  "nulla mauris lacus",
  "rhoncus eget dapibus et",
  "convallis sed odio",
  "curabitur venenatis sit amet magna at mattis",
  "curabitur luctus",
  "nunc sit amet congue mattis",
  "nulla augue scelerisque massa",
  "eu euismod augue lorem a nisl",
  "pellentesque ut dolor nisi",
  "integer auctor lacus elit",
  "vel venenatis mi condimentum et",
  "morbi eget purus leo",
  "maecenas venenatis viverra feugiat",
  "curabitur a ligula at lacus lacinia facilisis",
  "vestibulum dapibus faucibus nisl id commodo",
  "morbi luctus imperdiet nisl",
  "ac tristique nulla pretium nec",
  "nunc suscipit quam ac nisi sagittis",
  "vitae fermentum tellus hendrerit",
  "fusce consectetur",
  "mi eu luctus lobortis",
  "sem mauris fringilla mi",
  "at pretium leo enim a nibh",
  "duis eu nisi faucibus",
  "pellentesque dui et",
  "pulvinar ex",
  "donec et interdum libero",
  "sit amet pulvinar nisl",
  "vivamus suscipit",
  "lorem aliquam venenatis semper",
  "libero ante fermentum dui",
  "a consectetur lacus neque eget eros",
  "in porta mi eu elementum pulvinar",
  "donec non augue sed leo efficitur tincidunt",
  "quisque a nibh eu mi finibus malesuada vel at nunc",
  "in eget urna congue",
  "feugiat lacus ac",
  "vestibulum sapien",
  "aliquam tincidunt lacus id purus eleifend elementum",
  "aliquam venenatis tincidunt ante at hendrerit",
  "in in orci at nulla vehicula venenatis pulvinar id",
  "morbi eu tincidunt ipsum",
  "curabitur convallis venenatis suscipit",
  "vestibulum tristique ac tortor ac laoreet",
  "phasellus volutpat",
  "enim sit amet commodo tristique",
  "leo sem hendrerit quam",
  "quis lacinia arcu ante vitae urna",
  "integer eleifend faucibus urna nec posuere",
  "duis ullamcorper risus a sollicitudin fermentum",
  "nunc porta nisl at fringilla ullamcorper",
];
